import type { Metadata } from "next";

import "./globals.css";
import SoftGradientOne from "./components/soft-gradients/soft-gradient-one";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SoftGradientOne />
        <div className="w-full h-full absolute backdrop-blur-[140px]">
          {children}
        </div>
      </body>
    </html>
  );
}
